{
	"creature_defs":[
		{
			"name":"BAT",
			"character_def":"BAT",
			"behavior_def":"DEFAULT_ENEMY",
			"acb_def":"DEFAULT_ENEMY",
			"skill_level":0,
			"information":{
				"name":"Bat",
				"general_group":"BAT",
				"variation_group":"NONE",
				"unique_group":"NONE"
			},
			"interactions_def":"DEFAULT_ENEMY",
			"equipment":{
				"weapon_def":"BAT_SONIC",
				"armor_def":"BAT_ARMOR"
			},
			"knowledges":{
			},
			"statistics":{
			},
			"health":{
			},
			"skills":{
			},
			"factions":{
			}			
		}
	]
}
